fcpx: Decode output of ffprobe before using it as string
Getting this stack trace otherwise:

```
Traceback (most recent call last):
  File "gesotioformatter.py", line 44, in do_save_to_uri
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/__init__.py", line 194, in write_to_file
    **adapter_argument_map
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 179, in write_to_file
    result = self.write_to_string(input_otio, **adapter_argument_map)
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/adapters/adapter.py", line 243, in write_to_string
    **adapter_argument_map
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio/plugins/python_plugin.py", line 128, in _execute_function
    return (getattr(self.module(), func_name)(**kwargs))
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 1182, in write_to_string
    return FcpxOtio(input_otio).to_xml()
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 193, in to_xml
    top_sequence = self._stack_to_sequence(project.tracks)
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 265, in _stack_to_sequence
    self._track_for_spine(track, idx, spine, compound_clip)
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 279, in _track_for_spine
    compound=compound
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 379, in _element_for_item
    asset_id = self._add_asset(item, compound_only=compound)
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 560, in _add_asset
    format_element = self._find_or_create_format_from(clip)
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 556, in _find_or_create_format_from
    format_element.set("name", self._clip_format_name(clip))
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 537, in _clip_format_name
    clip.media_reference.target_url
  File "/home/thiblahute/devel/gstreamer/gst-build/subprojects/OpenTimelineIO/opentimelineio_contrib/adapters/fcpx_xml.py", line 95, in format_name
    if "1920" in frame_size:
TypeError: a bytes-like object is required, not 'str'
```

And add a unit test (the mock avalaibility logic comes from
test_detection_plugin.py)