Python 3.12 support / imp module deleted (#1669)
* Add python 3.12 to CI matrix

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

* Stop using imp module it's deprecated since python 3.4 and removed in python 3.12

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

* Fix AttributeError: 'VendorImporter' object has no attribute '_path' in Python 3.12 for autogen_serialized_datamodel.py

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

* Update pybind11 submodule to latest tag (v2.11.1)

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

* Fix opentimelineio.url_utils.filepath_from_url for windows URL in python 3.12

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

* In python-package.yml workflow upgrade pypa/cibuildwheel to v2.16.2 to support python 3.12

Signed-off-by: Evan Blaudy <evan@cg-wire.com>

---------

Signed-off-by: Evan Blaudy <evan@cg-wire.com>